name: cogni_chat
description: CogniChat app using chatGPT.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: '>=3.7.12'

dependency_overrides:

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # firebase
  firebase_core: 2.11.0
  firebase_messaging: 14.5.0
  firebase_analytics: 10.3.0
  firebase_crashlytics: 3.2.0

  # slang
  slang: 3.17.0
  slang_flutter: 3.17.0

  # riverpod
  riverpod: 2.3.6
  flutter_riverpod: 2.3.6

  freezed_annotation: 2.2.0
  json_annotation: 4.8.1
  copy_with_extension: 5.0.2
  go_router: 7.0.0

  dio: 5.1.1
  dio_http_formatter: 3.1.0
  connectivity_plus: 3.0.6

  flutter_displaymode: 0.6.0
  animated_text_kit: 4.2.2
  flutter_animate: 4.1.1+1
  flutter_spinkit: 5.2.0
  keyboard_dismisser: 3.0.0

  gap: 3.0.0
  flextras: 1.0.0

  flutter_svg: 2.0.5

  sqflite: 2.2.8+1
  shared_preferences: 2.1.0
  encrypt: 5.0.1

  quiver: 3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: 4.0.0+1

  build_runner: 2.3.3

  freezed: 2.3.3
  json_serializable: 6.6.2
  copy_with_extension_gen: 5.0.2
  go_router_builder: 2.0.0

flutter_gen:
  output: lib/gen/
  line_length: 100

flutter:
  uses-material-design: true

  assets:
    - assets/images/general/
    - assets/images/launch/

  fonts:
    - family: NotoSans
      fonts:
        - asset: fonts/NotoSans-Regular.ttf
          weight: 400
        - asset: fonts/NotoSans-Medium.ttf
          weight: 500
        - asset: fonts/NotoSans-SemiBold.ttf
          weight: 600
        - asset: fonts/NotoSans-Bold.ttf
          weight: 700
    - family: Orbitron
      fonts:
        - asset: fonts/Orbitron-Regular.ttf
          weight: 400
        - asset: fonts/Orbitron-Medium.ttf
          weight: 500
        - asset: fonts/Orbitron-SemiBold.ttf
          weight: 600
        - asset: fonts/Orbitron-Bold.ttf
          weight: 700